# Site settings
title: Eastern Panhandle Web Tech
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  All things web technology from web design to software engineering to systems administration. We meet on the third Tuesday of each month in downtown Martinsburg, WV.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://epwebtech.com" # the base hostname & protocol for your site
twitter_username: epwebtech
github_username:  epwebtech

# Build settings
markdown: kramdown

# Default Settings

# defaults:
#  -
#    scope:
#      path: "" # an empty string here means all files in the project
#      type: "posts" # previously `post` in Jekyll 2.2.
#    values:
#      author: Brad Hopkins
#      authorbio: I bought my first computer - an Apple Performa 6320 - when I was in college and have been building websites ever since. I like long walks in Illustrator and candle lit dinners with ExpressionEngine.
#      authorphoto: /images/bio-gbradhopkins.jpg
#      layout: "post"
      
      